### ISSUE TITLE
TINRS Tuesday

### ISSUE THREAD

**Issue by gitdistill** [boourns/synthmodes#27]
Should be a fairly simple one, but I just got the module and since the two main knobs X and Y are contextual per algorithm seemed like a good candidate.

Manual for reference: http://thisisnotrocketscience.nl/TINRS%20Tuesday%20Manual%20v1.2.pdf

**Comment by boourns** [comment]
closed: rank is under 1000

**Comment by boourns** [comment]
closed: rank is under 1000
