### ISSUE TITLE
Warps / Warps Parasites

### ISSUE THREAD

**Issue by boourns** [boourns/synthmodes#3]
This would be a good candidate for Modes.

I own the module so I plan on doing it in the next couple months, only thing preventing me from doing it now is building versions of the icons, maybe in SVG

**Comment by delta-6400** [comment]
@boourns 
I [exported .svg's](https://www.dropbox.com/sh/yqg2gh2fsem5ld0/AAAuD81mkCYaw3M2Kjcc1jU4a?dl=0) of the various icons from the [Warps Panel .ai](https://github.com/pichenettes/eurorack/blob/master/warps/hardware_design/panel/warps.ai).


I won't have time to work on this for a week or two probably, but feel free to tackle it if you want!

**Comment by boourns** [comment]
done, will be in next release

thanks @delta-6400 for the icons!
