### ISSUE TITLE
Plaits

### ISSUE THREAD

**Issue by boourns** [boourns/synthmodes#4]
Would be a good module to add.  Could reuse the existing Mutable module's CSS for knobs, maybe make it similar to Braids in terms of what to document.

Needs icons though.

**Comment by gitdistill** [comment]
fyi gonna try and work on this. I got the icons from the MI github panel design. Since source is vector (.ai) I can make them svg's which will be nicer. Those could either be inline svg's or just references to image in same directory in a subfolder. Do you have a preference? If referenced as img should I put an assets/images or an images folder in the plaits html folder? Not sure how that will work with your build process.

Still early stages, but commenting in case someone is gonna take this up and we don't duplicate work.

**Comment by boourns** [comment]
@gitdistill that is awesome, thank you!

inline SVGs or references to image in same directory should both "just work" on all platforms.  If not, I'll fix the build process to do so.

**Comment by boourns** [comment]
@gitdistill did you get anywhere on documenting Plaits? If you have anything done and want to pass the torch just open a PR or paste it here and I can wrap it up, just let me know

**Comment by gitdistill** [comment]
@boourns Yea. I basically took a pass at the manual oontent attempting to standardize and shorten. Especially the contextual parameter names that would go under visual of the corresponding knob

Sorry got swamped at work, I also have an idea in my head of how I would layout, just wanted to start with content. Happy to hand off, but also gonna have time this weekend to work on.

Lastly, have the source .ai file that was gonna use to spit out the svg's of the icons, but attaching here as well.

[plaits_v50.ai.zip](https://github.com/boourns/synthmodes/files/2823575/plaits_v50.ai.zip)
[plaits.txt](https://github.com/boourns/synthmodes/files/2823568/plaits.txt)

also thinking to add an issue for TNRS Tues as I just got one and will totally need a ref. I can help with that.

**Comment by boourns** [comment]
> Happy to hand off, but also gonna have time this weekend to work on.

If you have a plan and are still interested in doing it I'm happy to let you keep going.  I'll work on other modules.  I don't own a Plaits myself so I'm in no rush for it ;)

Just be sure that the result is an original work, nothing that would be considered a direct rip-off of the module manuals.  What you have in the text file looks great.

Cheers

**Comment by gitdistill** [comment]
@boourns sweet! will keep going. the actual design layout of the page will be original, the text content is an edit of MI online manual, but is stated as being under the CC-BY-SA 3.0 which, with attribution and link which I can add in a discreet location in a footer, would be compatible with this projects cc by 4.0, license. Can also check wtih MI i've been a forum member for a long time.

**Comment by boourns** [comment]
I have chatted with Emilie about the app and she had no concerns previously but up to you.  Cheers

**Comment by gitdistill** [comment]
#25

**Comment by boourns** [comment]
fixed in #25
