### ISSUE TITLE
web: repeated headings on w/

### ISSUE THREAD

**Issue by gmarinov** [boourns/synthmodes#48]
on https://synthmodes.com/modules/mannequins_w/
screenshots below.
did I miss doing something I should have?

<img width="671" alt="Screenshot 2019-07-08 at 19 18 20" src="https://user-images.githubusercontent.com/14101296/60832996-36ad7280-a1b5-11e9-9de8-3bf30bf643a7.png">
<img width="681" alt="Screenshot 2019-07-08 at 19 18 25" src="https://user-images.githubusercontent.com/14101296/60832997-36ad7280-a1b5-11e9-80fd-9e708be29889.png">
<img width="640" alt="Screenshot 2019-07-08 at 19 18 32" src="https://user-images.githubusercontent.com/14101296/60832998-37460900-a1b5-11e9-8b3c-e6bfe0a11624.png">
<img width="628" alt="Screenshot 2019-07-08 at 19 18 38" src="https://user-images.githubusercontent.com/14101296/60833000-37460900-a1b5-11e9-82a9-64b637cf867b.png">

**Comment by boourns** [comment]
I'll compare it with others, to be honest the website builder is a hack so it's my fault

Am working this week on an app update to get this into the app!  Sorry for the delay.  Have been busy getting Spectrum (https://apps.apple.com/app/id1467384251#?platform=ipad) out the door.

**Comment by boourns** [comment]
Ah yeah, it's just that most pages don't include their own headers as it gets injected either by the app or by web. Just pushed a fix
