### ISSUE TITLE
Changed name of Clouds Parasites reverb mode

### ISSUE THREAD

**Issue by NoraCodes** [boourns/synthmodes#62]
At the request of Emilie Gillet, the [main Parasites repo](https://github.com/mqtthiqs/parasites) has changed the name of the Clouds Parasites reverb mode to "Miverb" (as in Mutable Instruments reVerb).

Would you accept an MR to update that name here?

**Comment by boourns** [comment]
Hi @NoraCodes, sorry for the delay.  I'd definitely accept a PR for that change.  If you have any questions let me know, and if you don't have time to do it let me know and I can do it myself.  Thanks for bringing that to my attention!
